spring.application.name=nextTasks


spring.datasource.url=jdbc:mysql://localhost:3306/db_nextTasks
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# JWT Configuration
app.jwt.secret=bXlTZWNyZXRLZXlGb3JOZXh0VGFza3NKV1RUb2tlbkdlbmVyYXRpb25NdXN0QmVMb25nRW5vdWdoRm9ySFMyNTY=
app.jwt.expiration=86400000

